### ISSUE TITLE
Error: Connection was successful, but database content is missing.

### ISSUE THREAD

**Issue by unclesamwk** [Jet-Rat/docker-otrs5#2]
otrs@4b04132acdaa:/$ /opt/otrs/bin/otrs.Console.pl Maint::Database::Check                                                                                        
Trying to connect to database 'DBI:mysql:database=otrs;host=otrs-db;' with user 'otrs'...
[Thu Nov 17 07:35:09 2016] otrs.Console.pl: DBD::mysql::st execute failed: Table 'otrs.valid' doesn't exist at /opt/otrs/Kernel/System/DB.pm line 666.
ERROR: OTRS-otrs.Console.pl-Maint::Database::Check-10 Perl: 5.22.1 OS: linux Time: Thu Nov 17 07:35:09 2016

 Message: Table 'otrs.valid' doesn't exist, SQL: 'SELECT * FROM valid'

 Traceback (158): 
   Module: Kernel::System::Console::Command::Maint::Database::Check::Run Line: 41
   Module: (eval) Line: 444
   Module: Kernel::System::Console::BaseCommand::Execute Line: 438
   Module: Kernel::System::Console::InterfaceConsole::Run Line: 86
   Module: /opt/otrs/bin/otrs.Console.pl Line: 38

[Thu Nov 17 07:35:09 2016] otrs.Console.pl: DBD::mysql::st fetchrow_array failed: fetch() without execute() at /opt/otrs/Kernel/System/DB.pm line 734.
Error: Connection was successful, but database content is missing.

**Comment by Jet-Rat** [comment]
My bad. After running containers you have to complete web-installation.
Added few words to README.md.
